require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  TargetRubyVersion: '2.7'
  Exclude:
    - sandbox/**/*
    - dummy-app/**/*
    - spec/dummy/**/*
    - vendor/bundle/**/*

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/VariableNumber:
  Enabled: false

# We use this extensively, the alternatives are not viable or desirable.
RSpec/AnyInstance:
  Enabled: false

# No need to make the code more complex for no real gain.
RSpec/MessageSpies:
  Enabled: false

# Let's consider legitimate to have multiple expectations within an example.
RSpec/MultipleExpectations:
  Enabled: false

# Allow to use subject as is, no big deal.
RSpec/NamedSubject:
  Enabled: false

# Let's set this to some really exaggerate value.
RSpec/NestedGroups:
  Max: 8

# We don't use the FactoryBot mixin
RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/VerifiedDoubles:
  # Sometimes you really need an "anything" double
  IgnoreSymbolicNames: true

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
    - db/migrate/**/*
    - bin/**/*

Style/ExplicitBlockArgument:
  Exclude:

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*

Rails/ReflectionClassName:
  Exclude:

RSpec/MultipleMemoizedHelpers:
  Exclude:

Rails/ApplicationRecord:
  Exclude:
    - db/migrate/*